return {
    Version = 2,
    CandidateId = 'baseline',
    ParentCandidateId = 'manual',
    Score = 0,
    SourceLog = 'C:/Users/Sepgi/AppData/Roaming/Forged Alliance Forever/logs/game_26823704.log',
    GeneratedAt = '2026-04-07T07:18:47Z',

    FactoryFloorEarly = 2,
    FactoryFloorMid = 3,
    FactoryFloorLate = 5,
    FactoryRecoveryStagnation = 85,

    ScoutMinCount = 5,

    ACUOpeningMaxDistance = 16,
    ACUMidMaxDistance = 24,
    ACULateMaxDistance = 38,

    SafeExpandHotspotCapBias = 0,
    BaseEngineerFloorMin = 3,
    BaseEngineerFloorBias = 0,
    EngineerFactoryRatioBias = 0,
    FactoryMassIncomeBias = 0,
    FactoryEnergyIncomeBias = 0,
    FactoryMassRatioBias = 0,
    FactoryEnergyRatioBias = 0,
    FactoryMassPerFactoryBias = 0,
    FactoryToMexCapBias = 0,
    FactoryTempoBias = 0,
    SafeExpandDistanceBias = 0,
    SafeExpandThreatCapBias = 0,
    SafeExpandEnemyBufferBias = 0,
    ReclaimQuotaTimeBias = 0,
    ReclaimScoreBias = 0,
    ReclaimQuotaBias = 0,
    ExpansionQuotaBias = 0,
    UpgradeTimeBias = 0,
    AirFactoryTimeBias = 0,
    RadarTimeBias = 0,
    PowerNeedRatioBias = 0,
}
