create schema if not exists autotune;

create table if not exists autotune.session_runs (
    session_id text primary key,
    overnight_session_id text null,
    session_kind text not null check (session_kind in ('economy', 'overnight')),
    run_dir text not null,
    map_name text null,
    base_seed bigint null,
    candidates integer null,
    games_per_candidate integer null,
    parallel_instances integer null,
    target_speed integer null,
    promoted boolean null,
    no_promote boolean null,
    promote_score_margin numeric null,
    require_mass_ratio_gain numeric null,
    min_mass_ratio_absolute numeric null,
    min_avg_game_time integer null,
    max_mass_ratio_regression numeric null,
    max_survival_regression numeric null,
    retest_top integer null,
    retest_games integer null,
    retest_maps text[] null,
    adaptive_mutation_sources integer null,
    failure_aware_mutation boolean null,
    baseline_score numeric null,
    baseline_avg_game_time numeric null,
    baseline_avg_mass_ratio numeric null,
    baseline_primary_failure_class text null,
    best_candidate text null,
    best_score numeric null,
    best_avg_game_time numeric null,
    best_avg_mass_ratio numeric null,
    best_primary_failure_class text null,
    margin numeric null,
    promotion_allowed boolean null,
    promotion_blocked_reasons text[] null,
    version integer null,
    fingerprint text null,
    git_commit text null,
    ai_matchup text null,
    opponent_key text null,
    created_at timestamptz not null default now(),
    ingested_at timestamptz not null default now(),
    raw_summary jsonb not null
);

create table if not exists autotune.candidate_results (
    session_id text not null references autotune.session_runs(session_id) on delete cascade,
    candidate_id text not null,
    parent_candidate_id text null,
    map_name text null,
    games integer null,
    score numeric null,
    win_rate numeric null,
    avg_game_time numeric null,
    avg_mass_ratio numeric null,
    primary_failure_class text null,
    runtime_clean boolean null,
    config_version integer null,
    promoted boolean not null default false,
    config_json jsonb null,
    raw_score jsonb null,
    created_at timestamptz not null default now(),
    primary key (session_id, candidate_id)
);

create table if not exists autotune.candidate_parameters (
    session_id text not null,
    candidate_id text not null,
    param_name text not null,
    param_value numeric not null,
    primary key (session_id, candidate_id, param_name),
    foreign key (session_id, candidate_id) references autotune.candidate_results(session_id, candidate_id) on delete cascade
);

create table if not exists autotune.game_results (
    session_id text not null,
    candidate_id text not null,
    log_name text not null,
    run_tag text null,
    instance integer null,
    log_path text null,
    ai_matchup text null,
    winner_name text null,
    winner_type text null,
    winner_score numeric null,
    warnings integer null,
    errors integer null,
    top_warning text null,
    overmind_event_types integer null,
    overmind_event_total integer null,
    top_overmind_event text null,
    game_time text null,
    game_time_seconds numeric null,
    session_time_seconds numeric null,
    run_time_seconds numeric null,
    startup_ok boolean null,
    config_loaded boolean null,
    config_path text null,
    sim_speed integer null,
    observer_only boolean null,
    raw_summary jsonb null,
    primary key (session_id, candidate_id, log_name),
    foreign key (session_id, candidate_id) references autotune.candidate_results(session_id, candidate_id) on delete cascade
);

create table if not exists autotune.game_player_stats (
    session_id text not null,
    candidate_id text not null,
    log_name text not null,
    player_name text not null,
    player_type text null,
    faction integer null,
    score numeric null,
    current_units integer null,
    kills_mass numeric null,
    loss_mass numeric null,
    mass_in numeric null,
    mass_out numeric null,
    mass_over numeric null,
    energy_in numeric null,
    energy_out numeric null,
    energy_over numeric null,
    is_overmind boolean not null default false,
    is_opponent boolean not null default false,
    raw_player jsonb null,
    primary key (session_id, candidate_id, log_name, player_name),
    foreign key (session_id, candidate_id, log_name) references autotune.game_results(session_id, candidate_id, log_name) on delete cascade
);

create table if not exists autotune.game_kpis (
    session_id text not null,
    candidate_id text not null,
    log_name text not null,
    run_tag text null,
    instance integer null,
    game_time_seconds numeric null,
    first_mex_1_time numeric null,
    first_mex_5_time numeric null,
    first_mex_8_time numeric null,
    first_factory_2_time numeric null,
    first_expand_dispatch_time numeric null,
    max_factory_total integer null,
    max_mex_ready integer null,
    expansion_orders_total numeric null,
    reclaim_field_orders_total numeric null,
    stagnation_seconds_est numeric null,
    overmind_mass_in numeric null,
    overmind_mass_out numeric null,
    opponent_mass_in numeric null,
    overmind_mass_in_ratio numeric null,
    mex_at_120 numeric null,
    fac_total_at_120 numeric null,
    mex_at_240 numeric null,
    fac_total_at_240 numeric null,
    mex_at_360 numeric null,
    fac_total_at_360 numeric null,
    mex_at_600 numeric null,
    fac_total_at_600 numeric null,
    mex_at_900 numeric null,
    fac_total_at_900 numeric null,
    raw_kpi jsonb null,
    primary key (session_id, candidate_id, log_name),
    foreign key (session_id, candidate_id, log_name) references autotune.game_results(session_id, candidate_id, log_name) on delete cascade
);

create table if not exists autotune.champions (
    session_id text not null,
    candidate_id text not null,
    map_name text null,
    opponent_key text null,
    ai_matchup text null,
    promoted_at timestamptz not null default now(),
    score numeric null,
    avg_game_time numeric null,
    avg_mass_ratio numeric null,
    version integer null,
    fingerprint text null,
    git_commit text null,
    config_json jsonb null,
    primary key (session_id, candidate_id),
    foreign key (session_id, candidate_id) references autotune.candidate_results(session_id, candidate_id) on delete cascade
);

create table if not exists autotune.overnight_runs (
    overnight_session_id text primary key,
    run_dir text not null,
    campaigns_requested integer null,
    campaigns_completed integer null,
    base_seed bigint null,
    map_name text null,
    candidates integer null,
    games_per_candidate integer null,
    parallel_instances integer null,
    target_speed integer null,
    no_promote boolean null,
    require_mass_ratio_gain numeric null,
    min_mass_ratio_absolute numeric null,
    min_avg_game_time integer null,
    retest_top integer null,
    retest_games integer null,
    retest_maps text[] null,
    promotions integer null,
    created_at timestamptz not null default now(),
    ingested_at timestamptz not null default now(),
    raw_summary jsonb not null
);

create table if not exists autotune.overnight_campaign_results (
    overnight_session_id text not null references autotune.overnight_runs(overnight_session_id) on delete cascade,
    campaign_session_id text not null,
    promoted boolean null,
    best_candidate text null,
    best_score numeric null,
    best_avg_game_time numeric null,
    best_avg_mass_ratio numeric null,
    best_primary_failure_class text null,
    baseline_score numeric null,
    baseline_avg_game_time numeric null,
    baseline_avg_mass_ratio numeric null,
    promotion_allowed boolean null,
    promotion_blocked_reasons text[] null,
    primary key (overnight_session_id, campaign_session_id)
);

create index if not exists ix_autotune_session_runs_map_opponent on autotune.session_runs(map_name, opponent_key);
create index if not exists ix_autotune_candidate_results_score on autotune.candidate_results(score desc);
create index if not exists ix_autotune_candidate_results_mass_ratio on autotune.candidate_results(avg_mass_ratio desc);
create index if not exists ix_autotune_candidate_parameters_name on autotune.candidate_parameters(param_name);
create index if not exists ix_autotune_game_results_matchup on autotune.game_results(ai_matchup, winner_name);
create index if not exists ix_autotune_game_kpis_mass_ratio on autotune.game_kpis(overmind_mass_in_ratio desc);
create index if not exists ix_autotune_champions_map_opponent on autotune.champions(map_name, opponent_key, promoted_at desc);
